AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'doc/**/*'
    - '.bundle/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: true