version: '3.8'

services:
  gem:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/gem
      - bundle_cache:/usr/local/bundle
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_APP_CONFIG=/usr/local/bundle
      - BUNDLE_JOBS=4
      - BUNDLE_RETRY=3
    command: bundle exec rake
    tty: true
    stdin_open: true

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/gem
      - bundle_cache:/usr/local/bundle
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_APP_CONFIG=/usr/local/bundle
      - BUNDLE_JOBS=4
      - BUNDLE_RETRY=3
      - COVERAGE=true
    command: bundle exec rake spec

  console:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/gem
      - bundle_cache:/usr/local/bundle
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_APP_CONFIG=/usr/local/bundle
    command: bundle exec bin/console
    tty: true
    stdin_open: true

volumes:
  bundle_cache: