services:
  gem:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/gem
      - bundle_cache:/usr/local/bundle
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_APP_CONFIG=/usr/local/bundle
      - BUNDLE_JOBS=4
      - BUNDLE_RETRY=3
      - GIT_AUTHOR_NAME=${GIT_USERNAME:-Default User}
      - GIT_AUTHOR_EMAIL=${GIT_EMAIL:-user@example.com}
      - GIT_COMMITTER_NAME=${GIT_USERNAME:-Default User}
      - GIT_COMMITTER_EMAIL=${GIT_EMAIL:-user@example.com}
    command: bundle exec rake
    tty: true
    stdin_open: true

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/gem
      - bundle_cache:/usr/local/bundle
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_APP_CONFIG=/usr/local/bundle
      - BUNDLE_JOBS=4
      - BUNDLE_RETRY=3
      - COVERAGE=true
    command: bundle exec rake spec

  console:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/gem
      - bundle_cache:/usr/local/bundle
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_APP_CONFIG=/usr/local/bundle
    command: bundle exec bin/console
    tty: true
    stdin_open: true

  local_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/gem
      - bundle_cache:/usr/local/bundle
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_APP_CONFIG=/usr/local/bundle
    command: bundle exec bin/local_dev.rb
    tty: true
    stdin_open: true

volumes:
  bundle_cache: